import type { Metadata } from 'next';
import { ArrowUpRight, CheckCircle2, CircleGauge, MessageSquareText, Layers3, TrendingUp } from 'lucide-react';
import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = { title: 'Why choose us', description: 'Discover the Host Cloud difference: one accountable digital partner, clear communication, and work tied to business outcomes.' };
const reasons = [{ icon: CircleGauge, title: 'Focused on forward motion', text: 'We turn big goals into a sequence of practical moves your team can see and act on.' }, { icon: MessageSquareText, title: 'Communication that respects your time', text: 'No black boxes. You always know what is happening, what is next, and why it matters.' }, { icon: Layers3, title: 'A connected point of view', text: 'Strategy, execution, and operations stay connected instead of becoming three separate projects.' }, { icon: TrendingUp, title: 'Built around your numbers', text: 'We define success early, track the signal, and use the learning to improve the next decision.' }];
export default function WhyChooseUsPage() { return <><SiteHeader /><main><section className="relative overflow-hidden border-b border-white/10 py-24 lg:py-32"><div className="hero-orb absolute -right-20 -top-40 h-[500px] w-[500px] rounded-full" /><div className="container-shell relative"><p className="eyebrow">Why choose us</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[1.08] tracking-[-0.05em] text-white sm:text-6xl">The advantage of having <span className="text-cyan-300">one good partner.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Less coordination. Better context. Faster decisions. Host Cloud gives your business the clarity and capability to keep moving.</p></div></section><section className="py-24 lg:py-32"><div className="container-shell grid gap-5 md:grid-cols-2">{reasons.map(({ icon: Icon, title, text }, index) => <div key={title} className="group rounded-3xl border border-white/10 bg-white/[0.03] p-8 transition hover:-translate-y-1 hover:border-cyan-300/40"><div className="flex items-center justify-between"><div className="rounded-2xl bg-cyan-300/10 p-3 text-cyan-300"><Icon size={25} /></div><span className="text-sm text-slate-600">0{index + 1}</span></div><h2 className="mt-12 text-2xl font-bold text-white">{title}</h2><p className="mt-3 max-w-md leading-7 text-slate-400">{text}</p><div className="mt-8 flex items-center gap-2 text-sm font-bold text-cyan-300"><CheckCircle2 size={17} /> A better way to work</div></div>)}</div></section><section className="bg-[#0b1b2d] py-24"><div className="container-shell flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow">Let&apos;s get specific</p><h2 className="mt-4 max-w-xl text-4xl font-bold tracking-[-0.04em] text-white">The right partnership starts with the right conversation.</h2></div><Link href="/contact-us" className="inline-flex shrink-0 items-center rounded-full bg-cyan-300 px-6 py-4 font-bold text-[#06111e]">Talk to Host Cloud <ArrowUpRight size={18} className="ml-2" /></Link></div></section></main><SiteFooter /></>; }
