import type { Metadata } from 'next';
import { ArrowUpRight, Compass, HeartHandshake, Lightbulb, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = { title: 'About us', description: 'Learn how Host Cloud helps ambitious businesses turn digital complexity into clear, measurable progress.' };

export default function AboutPage() { return <><SiteHeader /><main><section className="relative overflow-hidden border-b border-white/10 py-24 lg:py-32"><div className="grid-glow absolute inset-0" /><div className="container-shell relative"><p className="eyebrow">About Host Cloud</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[1.08] tracking-[-0.05em] text-white sm:text-6xl">A small, sharp team for <span className="text-cyan-300">big ambitions.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">We combine strategy, design, technology, and operations to help modern businesses find their edge and keep it.</p></div></section><section className="py-24 lg:py-32"><div className="container-shell grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Our point of view</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.04em] text-white sm:text-5xl">Digital work should feel like a <span className="text-cyan-300">competitive advantage.</span></h2></div><div className="space-y-5 text-lg leading-8 text-slate-400"><p>Too often, businesses are forced to coordinate disconnected specialists, decode jargon, and chase work that never quite reaches the finish line.</p><p>Host Cloud is designed differently. We bring the capabilities you need into one accountable partnership, with practical advice and visible progress at every stage.</p></div></div></section><section className="bg-[#0b1b2d] py-24"><div className="container-shell"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{([['01', 'Stay curious', 'The best answers start with better questions.', Compass], ['02', 'Make it useful', 'Beautiful work should also make work easier.', Lightbulb], ['03', 'Own the outcome', 'We care about results, not just deliverables.', ShieldCheck], ['04', 'Work like partners', 'Clear, kind collaboration creates better work.', HeartHandshake]] as [string, string, string, typeof Compass][]).map(([number, title, text, Icon]) => <div key={number} className="border-t border-cyan-300/30 pt-5"><Icon className="text-cyan-300" size={24} /><p className="mt-8 text-xs font-bold tracking-[0.18em] text-slate-500">{number}</p><h3 className="mt-3 text-xl font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section><section className="py-24 text-center"><div className="container-shell"><p className="eyebrow">Built for the journey</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-bold tracking-[-0.04em] text-white">Let&apos;s turn your next challenge into a clearer path.</h2><Link href="/contact-us" className="mt-8 inline-flex items-center rounded-full bg-cyan-300 px-6 py-4 font-bold text-[#06111e]">Meet the team <ArrowUpRight size={18} className="ml-2" /></Link></div></section></main><SiteFooter /></>; }
